#KERNELSRCDIR = /home/dionisio/odroid-x/kernel_4412
KERNELSRCDIR = /home/noriaki/work/odroid-x/3.0.15/kernel_4412
#KERNELSRCDIR = /home/noriaki/work/odroid-x/3.1.xx/kernel_4412
BUILD_DIR := $(shell pwd)
VERBOSE = 0

#
obj-m := memtest.o

#
memtest-objs := kernel.o

all:
	make -C $(KERNELSRCDIR) SUBDIRS=$(BUILD_DIR) KBUILD_VERBOSE=$(VERBOSE) modules

clean:
	rm -f *.o
	rm -f *.ko
	rm -f *.mod.c
	rm -f *~

